#ifndef _MAP_H_
#define _MAP_H_

#include "../typedefs.h"
#include "./prefetch_queue.h"

#include "./operations/ADD.h"
#include "./operations/OR.h"
#include "./operations/ADC.h"
#include "./operations/SBB.h"
#include "./operations/AND.h"
#include "./operations/SUB.h"
#include "./operations/XOR.h"
#include "./operations/CMP.h"
#include "./operations/INC.h"
#include "./operations/DEC.h"
#include "./operations/PUSH.h"
#include "./operations/POP.h"
#include "./operations/DAA.h"
#include "./operations/DAS.h"
#include "./operations/AAA.h"
#include "./operations/AAS.h"
#include "./operations/PUSHA.h"
#include "./operations/POPA.h"
#include "./operations/BOUND.h"
#include "./operations/ARPL.h"
#include "./operations/IMUL.h"
#include "./operations/INSB.h"
#include "./operations/INSW_D.h"
#include "./operations/OUTSB.h"
#include "./operations/OUTSW_D.h"
#include "./operations/JO_SHORT.h"
#include "./operations/JNO_SHORT.h"
#include "./operations/JB_SHORT.h"
#include "./operations/JNB_SHORT.h"
#include "./operations/JZ_SHORT.h"
#include "./operations/JNZ_SHORT.h"
#include "./operations/JBE_SHORT.h"
#include "./operations/JNBE_SHORT.h"
#include "./operations/JS_SHORT.h"
#include "./operations/JNS_SHORT.h"
#include "./operations/JP_SHORT.h"
#include "./operations/JNP_SHORT.h"
#include "./operations/JL_SHORT.h"
#include "./operations/JNL_SHORT.h"
#include "./operations/JLE_SHORT.h"
#include "./operations/JNLE_SHORT.h"
#include "./operations/TEST.h"
#include "./operations/XCNG.h"
#include "./operations/MOV.h"
#include "./operations/LEA.h"
#include "./operations/NOP.h"

void map_operations_to_opcode_maps(void);

#endif // _MAP_H_