#ifndef _CONFIG_H_
#define _CONFIG_H_

/* predefined values for registers at reset and power-up */

#define CONF_RESET_DEFAULT_CS 0xF000 
#define CONF_RESET_DEFAULT_DS 0x0000
#define CONF_RESET_DEFAULT_ES 0x0000
#define CONF_RESET_DEFAULT_SS 0x0000
#define CONF_RESET_DEFAULT_FS 0x0000
#define CONF_RESET_DEFAULT_GS 0x0000

#define CONF_RESET_DEFAULT_EAX_AL 0x00
#define CONF_RESET_DEFAULT_EAX_AH 0x00
#define CONF_RESET_DEFAULT_EAX_MSB 0x0000

#define CONF_RESET_DEFAULT_EDX_DH 0x3 // Device ID : 3 indicates i80386 component 
#define CONF_RESET_DEFAULT_EDX_DL 0x3 // Revision Level ID 

#define CONF_RESET_DEFAULT_EIP_IP 0xFFF0
#define CONF_RESET_DEFAULT_EIP_msb 0x0000

#define CONF_RESET_DEFAULT_EFLAG_CARRY 0
#define CONF_RESET_DEFAULT_EFLAG_RES1 1
#define CONF_RESET_DEFAULT_EFLAG_PARITY 0
#define CONF_RESET_DEFAULT_EFLAG_RES3 0
#define CONF_RESET_DEFAULT_EFLAG_AUX_CARRY 0
#define CONF_RESET_DEFAULT_EFLAG_RES5 0
#define CONF_RESET_DEFAULT_EFLAG_ZERO 0
#define CONF_RESET_DEFAULT_EFLAG_SIGN 0
#define CONF_RESET_DEFAULT_EFLAG_TRAP 0
#define CONF_RESET_DEFAULT_EFLAG_INTR_ENABLE 0
#define CONF_RESET_DEFAULT_EFLAG_DIREC 0
#define CONF_RESET_DEFAULT_EFLAG_OVERF 0
#define CONF_RESET_DEFAULT_EFLAG_IO_PREV_LEV 0
#define CONF_RESET_DEFAULT_EFLAG_NESTED_TASK 0
#define CONF_RESET_DEFAULT_EFLAG_RES15 0
#define CONF_RESET_DEFAULT_EFLAG_RESUME 0
#define CONF_RESET_DEFAULT_EFLAG_VIRT_8086_MODE 0
#define CONF_RESET_DEFAULT_EFLAG_RES18_31 0



/* Pins power up  values */
#define CONF_PIN_BUSY_POW_UP 0
#define CONF_PIN_RESET_POW_UP 0


#endif // _CONFIG_H_