#ifndef _ModRM_map_H_
#define _ModRM_map_H_
#include <stdio.h>
void disp32(void);
void BXSI(void);
void BXSI_disp8(void);
void BXSI_disp16(void);
void EAX_AX_AL(void);
void BXDI(void);
void BXDI_disp8(void);
void BXDI_disp16(void);
void ECX_CX_CL(void);
void EDX_DX_DL(void);
void BPDI(void);
void BPDI_disp8(void);
void BPDI_disp16(void);
void EBX_BX_BL(void);
void SI(void);
void SI_disp8(void);
void SI_disp16(void);
void ESP_SP_AH(void);
void DI(void);
void DI_disp8(void);
void DI_disp16(void);
void EBP_BP_CH(void);
void disp16(void);
void BP_disp8(void);
void BP_disp816(void);
void ESI_SI_DH(void);
void BX(void);
void BX_disp8(void);
void BX_disp16(void);
void EDI_DI_BH(void);
void EAX(void);
void disp8_EAX(void);
void disp32_EAX(void);
void ECX(void);
void disp8_ECX(void);
void disp32_ECX(void);
void EDX(void);
void disp8_EDX(void);
void disp32_EDX(void);
void EBX(void);
void disp8_EBX(void);
void disp32_EBX(void);
void SIB(void);
void disp8_SIB(void);
void disp32_SIB(void);
void EBP(void);
void disp8_EBP(void);
void disp32_EBP(void);
void ESI(void);
void disp8_ESI(void);
void disp32_ESI(void);
void EDI(void);
void disp8_EDI(void);
void disp32_EDI(void);

#endif // _ModRM_map_H_
