#ifndef _SIB_map_H_
#define _SIB_map_H_
#include <stdio.h>
void EAX_2(void);
void EAX_4(void);
void EAX_8(void);
void ECX_2(void);
void ECX_4(void);
void ECX_8(void);
void EDX_2(void);
void EDX_4(void);
void EDX_8(void);
void EBX_2(void);
void EBX_4(void);
void EBX_8(void);
void none(void);
void non_2(void);
void non_4(void);
void non_8(void);
void EBP_2(void);
void EBP_4(void);
void EBP_8(void);
void ESI_2(void);
void ESI_4(void);
void ESI_8(void);
void EDI_2(void);
void EDI_4(void);
void EDI_8(void);

#endif // _SIB_map_H_
